### ISSUE TITLE
No binding generated for "DOMStringMap_deleter" function

### ISSUE THREAD

**Issue by denis-sh** [skoppe/spasm#41]
A minimal app (like DOM example) has dependency on all 3 `DOMStringMap` functions (and all 3 are in list returned by `wasmFile.getFunctionsToGenerateBindingsFor()`), but `DOMStringMap_deleter` function binding is not generated resulting in:

    LinkError: WebAssembly.instantiate(): Import #1020 module="env" function="DOMStringMap_deleter" error: function import requires a callable.

**Comment by denis-sh** [comment]
This is the only missing binding, if it's manually added like this:

    DOMStringMap_deleter: (rawResult, ctx, nameLen, namePtr) => { /* TODO */ },

Then the project works.

Maybe it's a mangling issue, as e.g. `DOMStringMap` getter function also accepting a `DOMString` is named  `DOMStringMap_getter__string`.

**Comment by skoppe** [comment]
That is strange. I have DOMStringMap in my unittests https://github.com/skoppe/spasm/blob/72b5ac83ea2a70378b0c2f1663edfd5d0b71262b/webidl/source/webidl/binding/test.d#L1151

Just for completeness' sake, you are running `dub spasm:webidl -- --bindgen`?

When I get back home I can try a minimal example myself, but in the meantime, if you have something testcase-like that would help as well.

**Comment by denis-sh** [comment]
Here is testcase:
1. Ensure `dub-1.20.0-beta.2` and `ldc-1.18.0` (or `ldc-1.20.0`) are installed and active.
2. Create and build project:
```
dub init -f sdl -n test-spasm spasm
cd test-spasm
echo 'dflags "-betterC"' >> dub.sdl
dub upgrade
dub run spasm:bootstrap-webpack
wget -O source/app.d https://raw.githubusercontent.com/skoppe/spasm/master/examples/dom/source/app.d
sed -i '/@safe/d' source/app.d
dub build --build=release --build-mode=allAtOnce
dub run spasm:webidl -- --bindgen
```
3. Check for `DOMStringMap_*` functions (only `test-spasm` will have `DOMStringMap_deleter`):
```
grep -oaE 'DOMStringMap_\w+' test-spasm
grep -oE 'DOMStringMap_\w+' spasm/modules/bindings.js
```

**Comment by skoppe** [comment]
I can confirm the `DOMStringMap_deleter` binding function is missing.

I had to add the following to the source/app.d file:

```
  elem.dataset.remove("something");
```

Otherwise the program wouldn't use `DOMStringMap`, hence no import nor binding. I assume you are using `dataset` as well, since that is the only thing that uses `DOMStringMap`.

Regardless, the binding should be created when used.

Will look into it. Thx.

**Comment by skoppe** [comment]
I have released `v0.2.0-beta.6`, it should be fixed there. Give dub a few minutes to update.

**Comment by denis-sh** [comment]
> I had to add the following to the source/app.d file:
> ...
> Otherwise the program wouldn't use `DOMStringMap`, hence no import nor binding. I assume you are using `dataset` as well, since that is the only thing that uses `DOMStringMap`.

No, the testcase I provided already caused `LinkError` because generated WASM file already had all 3 `DOMStringMap` functions as dependencies.

Is it unexpected? Did you get linker failure with example provided?

**Comment by denis-sh** [comment]
> Is it unexpected? Did you get linker failure with example provided?

I see, with `v0.2.0-beta.6` list of dependencies/bindings is rather short. It was very long and contained all 3 `DOMStringMap` functions for `v0.1.13`

**Comment by skoppe** [comment]
So the bindgen tool looks at the compiled wasm binary and only creates the glue code for the actual imports, not for everything, otherwise you'll end up with half a megabyte of js glue code. 

I thought v0.1.13 already did that, but it appears not to.

Regardless, there was still a problem with `DOMStringMap_deleter` not being generated. That should be fixed now.

**Comment by denis-sh** [comment]
> I thought v0.1.13 already did that, but it appears not to.

Yes, it did. And `DOMStringMap_deleter` as well as a lot of other symbols were returned by `wasmFile.getFunctionsToGenerateBindingsFor()` when analyzing WASM binary. So old spasm version somehow actually added these dependencies to WASM binary. If one removes all imports from `app.d` then no dependencies were added.

> That should be fixed now.

Thank you for quickly fixing the problem. Unfortunately I still can't run the example because of #43
